name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # sempre que você fizer push na branch main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do código
      - uses: actions/checkout@v3

      # Instala Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # Instala dependências
      - run: npm install

      # Gera o build do Astro
      - run: npm run build

      # Publica na branch gh-pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages